version: "3.9"

services:
    postgres:
        image: postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: dbaction
            POSTGRES_DB: dbaction_db
            POSTGRES_HOST_AUTH_METHOD: trust

volumes:
    postgres-data:
