name: publish

on:
    workflow_run:
        workflows: test
        branches: main
        types: completed

jobs:
    publish:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - run: |
                  pnpm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
                  pnpm ci
                  pnpm publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
