name: test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/checkout@v2
            - name: Start Docker Compose
              run: docker-compose up -d
            - name: Install Dependencies
              run: pnpm install
            - name: Build
              run: pnpm run build
            - name: Lint
              run: pnpm run lint
            - name: Test
              run: pnpm run test
